SELECT [PON]
      ,[Atividade]
      ,[Inicio_Previsto]
      ,[Termino_Atividade]
      ,[TP_Atividade]
      ,[Intervalo]
      ,[Status]
      ,[Cidade]
      ,[Detalhe_Atividade]
      ,[DT_Ag_Execucao]
      ,[Segmento]
      ,[Categoria_Cliente]
      ,[Duracao]
      ,[Rede_Acesso]
      ,[Matricula_Oper]
      ,[Nome_Oper]
      ,[Status_Final]
      ,[Grupo_Info]
      ,[Tipo_Servico]
      ,[CLUSTER_ZEUS]
      ,[GERENCIA]
      ,[ORIGEM_ORDENS]
      ,[CARGA_CONF]
      ,[MATRICULA_CONF]
      ,[INICIO_SLOT]
      ,[FIM_SLOT]
      ,[CHEGADA_SLOT]
FROM [TELECOM].[dbo].[Tb_Efetividade] WITH (NOLOCK)
